### ISSUE TITLE
[EPIC]: Create a single helm chart

### ISSUE THREAD

**Issue by Zelldon** [camunda-community-hub/camunda-cloud-helm#124]
One helm chart to rule them all. 

Create one single chart which contains all applications as sub charts.

### Todo:

- [x] Create Parent chart https://github.com/camunda-community-hub/camunda-cloud-helm/pull/135
- [x] Copy Zeebe cluster chart https://github.com/camunda-community-hub/camunda-cloud-helm/pull/135
  - [x] Refactor old values file, introduce better sectioning/grouping 
  - [x] Iterate over README and properties documentation
  - [x] First release https://github.com/camunda-community-hub/camunda-cloud-helm/releases/tag/ccsm-helm-0.0.1
- [x] Copy Operate chart https://github.com/camunda-community-hub/camunda-cloud-helm/pull/139
  - [x] Per default enabled
- [x] Copy Tasklist chart https://github.com/camunda-community-hub/camunda-cloud-helm/pull/142
  - [x] Per default enabled
- [x]  Separate Gateway as sub chart https://camunda.slack.com/archives/C02UT3T8DQR/p1643631277348409 https://github.com/camunda-community-hub/camunda-cloud-helm/pull/145
- [x] Add Notes.txt - is show when installing helm chart https://codersociety.com/blog/articles/helm-best-practices#4-document-your-charts
- [x] Disable ingress per default https://github.com/camunda-community-hub/camunda-cloud-helm/pull/150
- [x] Document value files https://helm.sh/docs/chart_best_practices/values/#document-valuesyaml
  - [x] Zeebe sub chart https://github.com/camunda-community-hub/camunda-cloud-helm/pull/141
  - [x] Operate sub chart https://github.com/camunda-community-hub/camunda-cloud-helm/pull/143
  - [x] Tasklist sub chart https://github.com/camunda-community-hub/camunda-cloud-helm/pull/145
- [x] Add labels https://github.com/camunda-community-hub/camunda-cloud-helm/pull/147
  - [x] #131  https://helm.sh/docs/chart_best_practices/labels/#standard-labels
- [x] Add REAME.md https://github.com/camunda-community-hub/camunda-cloud-helm/pull/151
  - [x] https://codersociety.com/blog/articles/helm-best-practices#4-document-your-charts
  - [x] remove or replace the old ones
  - [x] Document all values in Readme
- [x] https://github.com/camunda-community-hub/camunda-cloud-helm/issues/149
  - [x] https://github.com/camunda-community-hub/camunda-cloud-helm/pull/154
- [x] Build a release https://github.com/camunda-community-hub/camunda-cloud-helm/releases/tag/ccsm-helm-0.0.10

**Comment by Zelldon** [comment]
All Sub tasks are done
